# Use an official Python runtime as the base image
FROM python:3.11.6

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file to the container
COPY requirements.txt ./

# Install app dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Bundle the app source
COPY . .

# Expose the port the app runs on
EXPOSE 7000

# Define the command to run your app
CMD ["uvicorn", "blood_fast:app", "--host", "0.0.0.0", "--port", "7000"]
